#!/usr/bin/env bash

curl -viN \
    -m 1 \
    -H "Host: localhost:5000" \
    -H "Upgrade: websocket" \
    -H "Connection: Upgrade" \
    -H "Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==" \
    -H "Sec-WebSocket-Version: 13" \
    -H "Origin: http://example.org" \
        http://localhost:5000/my/channel

if test $? -eq 28; then
    exit 0
else
    exit 1
fi